ALTER TABLE panel_sessions ADD COLUMN csrf CHAR(64) NOT NULL;
ALTER TABLE panel_sessions ADD COLUMN password_fingerprint CHAR(64) NOT NULL;
ALTER TABLE panel_sessions ADD COLUMN authenticated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD CONSTRAINT user_parent FOREIGN KEY(parent_customer_id) REFERENCES users(id);
ALTER TABLE domains ADD COLUMN server_id BIGINT REFERENCES stalwart_servers(id);
ALTER TABLE email_accounts ADD COLUMN server_id BIGINT REFERENCES stalwart_servers(id);
ALTER TABLE api_sync_jobs ADD COLUMN server_id BIGINT REFERENCES stalwart_servers(id);
ALTER TABLE api_sync_jobs ADD COLUMN payload_encrypted TEXT;
ALTER TABLE email_accounts ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE domains ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE packages ADD CONSTRAINT package_limits CHECK (min_email_accounts>=1 AND max_email_accounts>=min_email_accounts AND min_domains>=1 AND max_domains>=min_domains AND billing_months BETWEEN 1 AND 120 AND duration_days BETWEEN 1 AND 3660 AND price>=0 AND COALESCE(promo_price,0)>=0 AND extra_domain_price>=0 AND storage_per_account_mb>0);
CREATE UNIQUE INDEX only_primary_server ON stalwart_servers(is_primary) WHERE is_primary=1 AND active=1;
CREATE UNIQUE INDEX alias_live ON email_aliases(lower(alias_email)) WHERE status<>'deleted';
CREATE UNIQUE INDEX user_email_ci ON users(lower(email));
CREATE TABLE page_content (language VARCHAR(20) NOT NULL, section VARCHAR(80) NOT NULL, content JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(language,section));
CREATE TABLE translations(language VARCHAR(20) NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, PRIMARY KEY(language,key));
CREATE TABLE notifications(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),recipient TEXT NOT NULL,subject TEXT NOT NULL,body_encrypted TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INT NOT NULL DEFAULT 0,run_after TIMESTAMPTZ NOT NULL DEFAULT now(),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE rust_reset_tokens(token_hash CHAR(64) PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id),expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ);
CREATE TABLE rust_change_plans(id BIGSERIAL PRIMARY KEY,server_id BIGINT NOT NULL REFERENCES stalwart_servers(id),server_version BIGINT NOT NULL,actor_id BIGINT NOT NULL REFERENCES users(id),calls JSONB NOT NULL,status TEXT NOT NULL DEFAULT 'ready',result JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),expires_at TIMESTAMPTZ NOT NULL DEFAULT now()+interval '15 minutes');
INSERT INTO languages(code,name,native_name) VALUES('vi','Vietnamese','Tiếng Việt'),('en','English','English');
INSERT INTO settings(key,value) VALUES('landing_brand_name','Email Business'),('site_language','vi');
